/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coca.project

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'coca.project.greeting' plugin.
 */
class CocaProjectPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('coca.project.greeting')
            }
        """)

      // Run the build
      val runner = GradleRunner.create()
          .forwardOutput()
          .withPluginClasspath()
          .withArguments("greeting", "--configuration-cache")
          .withProjectDir(projectDir)
      val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'coca.project.greeting'"))
      val runner2 = GradleRunner.create()
          .forwardOutput()
          .withPluginClasspath()
          .withArguments("greeting", "--configuration-cache")
          .withProjectDir(projectDir)

      val result2 = runner2.build()
      assertTrue(result2.output.contains("SUCCESS"))
      assertTrue(result2.output.contains("Configuration cache entry reused."))
    }
}
