/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coca.project

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class CocaProjectPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            if (project.hasProperty("foo")) {
                task.doFirst {
                    println("doing this first")
                }
            }

            task.doLast {
                println("Hello from plugin 'coca.project.greeting'")
            }
        }
    }
}
